version: '3'
services:
  mall-admin:
    image: openjdk:8u342-jdk-oracle
    container_name: mall-admin
    entrypoint: ["java", "-jar","-Dspring.profiles.active=prod", "/mall-admin-1.0-SNAPSHOT.jar", "-Xms64m -Xmx256m -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom "]
    ports:
      - 28082:8080
    volumes:
      - /mydata/mall/app/mall-admin-1.0-SNAPSHOT.jar:/mall-admin-1.0-SNAPSHOT.jar
      - /mydata/mall/app/mall-admin/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - mysql:db #可以用db这个域名访问mysql服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
        reservations:
          memory: 50M
  mall-search:
    image: openjdk:8u342-jdk-oracle
    container_name: mall-search
    entrypoint: ["java", "-jar","-Dspring.profiles.active=prod", "/mall-search-1.0-SNAPSHOT.jar", "-Xms64m -Xmx256m -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom "]
    ports:
      - 28081:8081
    volumes:
      - /mydata/mall/app/mall-search-1.0-SNAPSHOT.jar:/mall-search-1.0-SNAPSHOT.jar
      - /mydata/mall/app/mall-search/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
      - mysql:db #可以用db这个域名访问mysql服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
        reservations:
          memory: 50M
  mall-portal:
    image: openjdk:8u342-jdk-oracle
    build: .
    container_name: mall-portal
    entrypoint: ["java", "-jar","-Dspring.profiles.active=prod", "/mall-portal-1.0-SNAPSHOT.jar", "-Xms64m -Xmx256m -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom "]
    ports:
      - 28085:8085
    volumes:
      - /mydata/mall/app/mall-portal-1.0-SNAPSHOT.jar:/mall-portal-1.0-SNAPSHOT.jar
      - /mydata/mall/app/mall-portal/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - mongo:mongo #可以用mongo这个域名访问mongo服务
      - mysql:db #可以用db这个域名访问mysql服务
      - rabbitmq:rabbit #可以用rabbit这个域名访问rabbitmq服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
        reservations:
          memory: 50M
  mall-auth:
    image: openjdk:8u342-jdk-oracle
    container_name: mall-auth
    entrypoint: ["java", "-jar","-Dspring.profiles.active=prod", "/mall-auth-1.0-SNAPSHOT.jar", "-Xms64m -Xmx256m -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom "]
    ports:
      - 28401:8401
    volumes:
      - /mydata/mall/app/mall-auth-1.0-SNAPSHOT.jar:/mall-auth-1.0-SNAPSHOT.jar
      - /mydata/mall/app/mall-auth/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
        reservations:
          memory: 50M
  mall-gateway:
    image: openjdk:8u342-jdk-oracle
    container_name: mall-gateway
    entrypoint: ["java", "-jar","-Dspring.profiles.active=prod", "/mall-gateway-1.0-SNAPSHOT.jar", "-Xms64m -Xmx256m -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom "]
    ports:
      - 28201:8201
    volumes:
      - /mydata/mall/app/mall-gateway-1.0-SNAPSHOT.jar:/mall-gateway-1.0-SNAPSHOT.jar
      - /mydata/mall/app/mall-gateway/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
        reservations:
          memory: 50M
  mall-monitor:
    image: openjdk:8u342-jdk-oracle
    container_name: mall-monitor
    entrypoint: ["java", "-jar","-Dspring.profiles.active=prod", "/mall-monitor-1.0-SNAPSHOT.jar", "-Xms64m -Xmx256m -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom "]
    ports:
      - 28101:8101
    volumes:
      - /mydata/mall/app/mall-monitor-1.0-SNAPSHOT.jar:/mall-monitor-1.0-SNAPSHOT.jar
      - /mydata/mall/app/mall-monitor/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
        reservations:
          memory: 50M