version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
      MYSQL_DATABASE: 'mall'
    ports:
      - 23306:3306
    volumes:
      - /mydata/mall/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /mydata/mall/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /mydata/mall/mysql/log:/var/log/mysql #日志文件挂载
      - /mydata/mall/mysql/db/:/docker-entrypoint-initdb.d/  #初始化脚本挂载
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
        reservations:
          memory: 50M
  redis:
    image: redis:7
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /mydata/mall/redis/data:/data #数据文件挂载
    ports:
      - 26379:6379
  nginx:
    image: nginx:1.22
    container_name: nginx
    volumes:
      - /mydata/mall/nginx/conf/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      - /mydata/mall/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - /mydata/mall/nginx/log:/var/log/nginx #日志文件挂载
    ports:
      - 28080:80
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=admin # 默认账号和密码是:guest
#      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - /mydata/mall/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - /mydata/mall/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    user: root
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - /mydata/mall/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /mydata/mall/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 29200:9200
      - 29300:9300
  logstash:
    image: logstash:7.17.3
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mydata/mall/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 24560:4560
      - 24561:4561
      - 24562:4562
      - 24563:4563
  kibana:
    image: kibana:7.17.3
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 25601:5601
  mongo:
    image: mongo:4
    container_name: mongo
    volumes:
      - /mydata/mall/mongo/db:/data/db #数据文件挂载
    ports:
      - 27017:27017
  nacos-registry:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos-registry
    environment:
      - "MODE=standalone"
    ports:
      - 28848:8848
